openapi: 3.0.0

info:
  title: Scraper API
  description: Web Scraper to request data via an REST API that is not provided through an API
  version: 1.0.0

servers:
  - url: http://todo.api.example.com/v1
    description: Main production server

paths:
  /learnrooms:
    get:
      summary: Returns a list of available learn rooms.
      responses:
        '200':
          description: A JSON array of learn rooms.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: 'B 309'
